### ISSUE TITLE
Unable to view results

### ISSUE THREAD

**Issue by kunal732** [awslabs/media-analysis-solution#13]
After uploading a video for analysis and waiting for it to complete. I go to the browse page and then click on the video to view results. The page shows up blank, nothing is there. 

Looking through the console I notice this issue. 
`DOMException: Failed to execute 'querySelector' on 'Document': '60-degrees-904c3cff-43c5-4fe2-bf50-d7240fa70194' is not a valid selector.`

Anyone else facing the same issue ?

I'm following this tutorial: https://s3.amazonaws.com/mae303/MediaAnalysisWorkshop.pdf

**Comment by dariushazimi** [comment]
Same issue here. It used to work before but for some reason I get javascript errors if you look at the source in developer tools on chrome.
```
Uncaught TypeError: Cannot read property 'type' of undefined
    at e.setFieldValue (onloadwff.js:71)
    at HTMLFormElement.formKeydownListener (onloadwff.js:71)
```

`DOMException: Failed to execute 'querySelector' on 'Document': '2013-d35a-446e-b180-b62c7ef7f971' is not a valid selector.`

**Comment by chrdavid** [comment]
Same result here, while using the guide from the blog (without building own package from source code): https://aws.amazon.com/de/blogs/machine-learning/get-started-with-automated-metadata-extraction-using-the-aws-media-analysis-solution/

As mentioned in the first answer of a similar issue at [Stackoverflow](https://stackoverflow.com/questions/37270787/uncaught-syntaxerror-failed-to-execute-queryselector-on-document)  and in the [CSS2.2 specs](https://www.w3.org/TR/CSS22/syndata.html#value-def-identifier) identifiers should not start with a digit when using 'querySelector'. In my case the identifier was '50-hotness-2b735386-5ffe-4149-9644-bd1710b659d6'.

**Comment by dariushazimi** [comment]
Has anyone been able to resolve this issue?

It used to work just fine about 2 months ago. !!
Thanks

**Comment by dariushazimi** [comment]
@kunal732  @chrdavid  have you guys been able to resolve this issue? still having the same issue.
thanks.

**Comment by dariushazimi** [comment]
> Same result here, while using the guide from the blog (without building own package from source code): https://aws.amazon.com/de/blogs/machine-learning/get-started-with-automated-metadata-extraction-using-the-aws-media-analysis-solution/
> 
> As mentioned in the first answer of a similar issue at [Stackoverflow](https://stackoverflow.com/questions/37270787/uncaught-syntaxerror-failed-to-execute-queryselector-on-document) and in the [CSS2.2 specs](https://www.w3.org/TR/CSS22/syndata.html#value-def-identifier) identifiers should not start with a digit when using 'querySelector'. In my case the identifier was '50-hotness-2b735386-5ffe-4149-9644-bd1710b659d6'.

@chrdavid How do you change the identifier and where do I find it? thanks

**Comment by chrdavid** [comment]
@dariushazimi no time to test yet, but [this commit](https://github.com/awslabs/media-analysis-solution/commit/1e1eed8cb8d6a79880c35e6c9fab6a80d098f9fc#diff-0411abe01572e5cdacc2fca7f25def10) from @georgebearden looks promising.

**Comment by georgebearden** [comment]
We have deployed a fix for this. Closing this issue now. Please feel free to reopen this issue or open a new issue if needed. Thanks.
