### ISSUE TITLE
How can i add text-rekognition.

### ISSUE THREAD

**Issue by portacha** [awslabs/media-analysis-solution#14]
I want to add text rekognition. In a few steps how can i do it?. just with lambda and steps or i need to change another service?

**Comment by aijunpeng** [comment]
The Media Analysis solution works with media files (audio, video and image). It can convert audio into text and create caption for a video. See more details here https://aws.amazon.com/solutions/media-analysis-solution/. If you want to extract text and data from scanned documents, I would recommend you to check out Amazon Textract (https://aws.amazon.com/textract/). You can always modify the solution to add new features that you need. Please provide more details of your use case so we can better understand your questions and provide help accordingly if you need further assistance. Thank you!

**Comment by aassadza** [comment]
For your information: This Solutions Implementation has been superseded by [AWS Content Analysis](https://aws.amazon.com/solutions/implementations/aws-content-analysis/).
