### ISSUE TITLE
Transcription results are not displaying

### ISSUE THREAD

**Issue by dariushazimi** [awslabs/media-analysis-solution#16]
The solution used to work before but for some reason, I get javascript errors if you look at the source in developer tools on chrome.

Uncaught TypeError: Cannot read property 'type' of undefined
    at e.setFieldValue (onloadwff.js:71)
    at HTMLFormElement.formKeydownListener (onloadwff.js:71)
DOMException: Failed to execute 'querySelector' on 'Document': '2013-d35a-446e-b180-b62c7ef7f971' is not a valid selector.

**Comment by georgebearden** [comment]
This is a duplicate of issue https://github.com/awslabs/media-analysis-solution/issues/13. Closing this issue now. Please follow up https://github.com/awslabs/media-analysis-solution/issues/13
