### ISSUE TITLE
Analysis video failed 

### ISSUE THREAD

**Issue by JustSmileGG** [awslabs/media-analysis-solution#18]
We are using Media Analysis Solution and we got a problem. We took your standard solution as a base for our backend architecture. We wrote our our frontend. We have a problem connected to your backend architecture - video analysis breaks for unknown reasons. The size of the video that breaks the video is around ~5GB. Sometimes a smaller video breaks analysis as well. 
Analysis breaks as well if you upload several videos from the same account (6 and more files of 2-3 GB each .mp4 format). 
Unfortunately, we can't say what the problem is because we can't see anything in the logs. Nothing to see in the service "stepFunctions" that are used as "StateMachine" in this mechanics. Nothing to see in the "Cloud Watch" (screenshots are attached, Screen_1-9 is a "StepFunction", LogsSample examples from Cloud Watch). We need your help to solve this. 
To replicate the error, you will need your template (links to the solution and GitHub are below) and remove the upload limitation of 100mb on the frontend and upload the file we've tested with here with the remaining screenshots: 
https://www.dropbox.com/sh/kztynnlh6jbcnvm/AAA_L39Stug_9Z88Js7gtf76a?dl=0 

Attached you will find the Logs from Functions from arn:aws:lambda:us-east-2:804662430691:function:FrontV11-MediaAnalysisFunction-1RDGN0SCSF6T6 : https://drive.google.com/file/d/1vintzR3mZ_7FjIkEeIEQP9mYWFm3X9nq/view?usp=sharing 
Unfortunately, the file is too big to be attached here.

Attachments
![image](https://user-images.githubusercontent.com/37774850/68212498-4f525b80-ffe2-11e9-9263-f57f5464dd33.png)

![image](https://user-images.githubusercontent.com/37774850/68212525-5c6f4a80-ffe2-11e9-9321-b8326c5fc2a7.png)

![image](https://user-images.githubusercontent.com/37774850/68212536-62652b80-ffe2-11e9-8397-34e6f7d61982.png)

![image](https://user-images.githubusercontent.com/37774850/68212554-698c3980-ffe2-11e9-8480-781da6aeaa7a.png)

![image](https://user-images.githubusercontent.com/37774850/68212569-6f821a80-ffe2-11e9-8048-3061e0e9f2e6.png)

**Comment by dscpinheiro** [comment]
Hi @JustSmileGG,

Sorry for the delay in the response.
From your screenshots, I can see the error message: _24 jobs for user. Maximum limit: 20_

There's a limit for the amount of concurrent jobs per account in Rekognition (https://docs.aws.amazon.com/rekognition/latest/dg/limits.html#limits-vstored-video):

> Amazon Rekognition Video supports a maximum of 20 concurrent jobs per account.

[This limit](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits_rekognition) can be changed by reaching out to [AWS support](https://console.aws.amazon.com/support/v1#/case/create?issueType=service-limit-increase).

**Comment by georgebearden** [comment]
Hi @JustSmileGG  - Closing this issue, but please let us know if you need additional assistance. Cheers.
