### ISSUE TITLE
Transcription may fail on certain files with multi-channel audio

### ISSUE THREAD

**Issue by leec3108** [awslabs/media-analysis-solution#19]
We're using the Media Analysis Solution in a project we're working on, and we noted that some multi-channel audio files will fail to transcribe with the current setup.  After speaking to AWS support, they determined that channel identification needed to be turned on in the request to AWS Transcribe. This should probably be on by default.

**Comment by ericquinones** [comment]
Hi @leec3108 
Thanks for the feedback. We'll take a look at that in our next update to the solution.

**Comment by aassadza** [comment]
For your information: This Solutions Implementation has been superseded by [AWS Content Analysis](https://aws.amazon.com/solutions/implementations/aws-content-analysis/).

**Comment by aassadza** [comment]
Closing issue as this repo is being retired. This Solutions Implementation has been superseded by AWS Content Analysis.
