### ISSUE TITLE
Manual S3 upload

### ISSUE THREAD

**Issue by davidfsmith** [awslabs/media-analysis-solution#5]
I've deployed this solution in my AWS account and using the UI it is working fine, however I need to be able to upload files greater than 100mb in size which is a limitation of the console.

> Note that if you want to upload a file over 100 MB, you will need to do so directly in the media analysis Amazon S3 bucket that was created as part of the AWS CloudFormation template. This 100 MB limit only occurs when using the demo console.

I've found the bucket created and from looking at the Lambda code it looks like `MediaAnalysis-MediaAnalysisFunction` is triggered when a file is added to the bucket in the `/private` directory - however when I've uploaded a file to this location the Lambda is triggered as expected but nothing appears to happen.

Is there a problem with manually uploading files to the S3 bucket or am I just uploading to the wrong location.  Thanks for any help / pointers.

**Comment by davidfsmith** [comment]
I've found the solution from reading the code.

> File previews are limited to 100MB or less for this demo page. Please upload file direclty to media analysis S3 bucket using the following naming convention:

`private/<Cognito Identity ID>/media/<UUID v4>/content/filename.ext`

https://github.com/awslabs/media-analysis-solution/blob/b4df98592953f71cf9bde5021978e5df82cc87e6/source/web_site/src/components/upload.js#L191

**Comment by dariushazimi** [comment]
@davidfsmith
We’re you able to upload larger file and perform analysis?
Did you just upload to the directory mentioned in the js file?

Also we’re you able to allow user sign up? Appears that you can’t change the user pool. Rather you have to define a new one. 

Thanks.

**Comment by davidfsmith** [comment]
Hello,  Yep I managed to make it work uploaded to the S3 bucket directly, but had to create the correct directory structure as per:

`private/<Cognito Identity ID>/media/<UUID v4>/content/filename.ext'`

I'll be honest that I didn't need to use the user sign up process as I just used the user created during the initial setup.

**Comment by dariushazimi** [comment]
Thanks, @davidfsmith, I am trying to deploy a similar solution using google speech api. 
Thanks for sharing
