### ISSUE TITLE
"SignUp is not permitted for this user pool", How to modify cognito?

### ISSUE THREAD

**Issue by dariushazimi** [awslabs/media-analysis-solution#8]
When I try the sign-up button, it says "SignUp is not permitted for this user pool". 
I have looked at Cognito but I can't find where I need to make a change to allow user sign up, or what to change on the template.

Any tips would be appreciated.

Thanks

**Comment by dariushazimi** [comment]
I believe the setting should be changed to` " AllowAdminCreateUserOnly: false".`
Is that the right solution?

**Comment by gsingh04** [comment]
Apologies for the delayed response. Yes, you are correct. If you want to make the change after the solution has been deployed, follow these steps:
1. Go to Cognito console
2. Select **Manage User Pools**
3. Chose the user pool created by the solution
4. Under **General settings** change **User sign ups allowed?** to **Allow users to sign themselves up**
5. Save the setting and this should allow your users to sign up.

Please resolve the issue.
